<?php

/**
 * @file
 * A block module that displays user name and role.
 */

/**
 * Implements hook_help().
 */
function d7_customblock_help($path, $arg) {
  switch ($path) {
    case "admin/help#customblock":
      return t("Displays user name and role");

    break;
  }
}

/**
 * Implements hook_menu().
 */
function d7_customblock_menu() {
  $items = array();

  $items['d7_customblock/user-info'] = array(
    'title' => 'User name and role',
    'description' => 'Displays user name and role',
    'page callback' => 'd7_customblock_info_page',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/people/user-info'] = array(
    'title' => 'User info',
    'description' => 'Configuration for d7 customblock module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d7_customblock_form'),
    'access arguments' => array('access administration configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: User info.
 */
function d7_customblock_info_page() {

  $default_id = variable_get('d7_customblock_uid', 0);
  $user_info = d7_customblock_user_info($default_id);

  $format = variable_get('d7_customblock_format', 0);
  $content = d7_customblock_content_format($format, $user_info);

  $page_array['d7_customblock_userinfo'] = $content;

  return $page_array;

}

/**
 * Page callback: d7 customblock settings.
 */
function d7_customblock_form($form, &$form_state) {

  $form['d7_customblock_uid'] = array(
    '#type' => 'textfield',
    '#title' => t('User id'),
    '#default_value' => variable_get('d7_customblock_uid', 0),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('Default user id.'),
    '#required' => TRUE,
  );

  $form['d7_customblock_format'] = array(
    '#type' => 'select',
    '#title' => t('Format'),
    '#options' => array(
      0 => t('Paragraph'),
      1 => t('List'),
    ),
    '#default_value' => variable_get('d7_customblock_format', 0),
    '#description' => t('Select format.'),
  );

  return system_settings_form($form);
}

/**
 * Implements validation from the Form API.
 *
 * @param array|null $form
 *   A structured array containing the elements and properties of the form.
 * @param array|null $form_state
 *   An array that stores information about the form's current state
 *   during processing.
 */
function d7_customblock_form_validate($form, &$form_state) {
  $user_uid = $form_state['values']['d7_customblock_uid'];
  if (!is_numeric($user_uid)) {
    form_set_error('d7_customblock_uid', t("You must enter a number for the User Id."));
  }
  elseif ($user_uid < 0) {
    form_set_error('d7_customblock_uid', t("User Id can't be negative."));
  }
}

/**
 * Implements hook_block_info().
 */
function d7_customblock_block_info() {
  $blocks['customblock'] = array(
    // The name that will appear in the block list.
    'info' => t('User name and role'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    'cache' => DRUPAL_CACHE_PER_ROLE,
    // Block shown only in nodes
    // 'visibility' => BLOCK_VISIBILITY_LISTED,
    // 'pages' => 'node/*',.
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function d7_customblock_block_view($delta = '') {

  switch ($delta) {
    case 'customblock':

      $default_id = variable_get('d7_customblock_uid', 0);
      $user_info = d7_customblock_user_info($default_id);

      $format = variable_get('d7_customblock_format', 0);
      $content = d7_customblock_content_format($format, $user_info);

      $block = [
        'subject' => t('User details'),
        'content' => $content,
      ];

      return $block;
  }

}

/**
 * Custom content function.
 *
 * @param int $default_uid
 *   User id.
 *
 * @return Object
 *   User info.
 */
function d7_customblock_user_info($default_uid) {

  $user_info = new stdClass();

  $user_to_show = user_load($default_uid);

  if (($user_to_show === FALSE) or ($default_uid == 0)) {
    $user_info->name = t('Anonimous user');
    $user_info->mail = '-';
    $user_info->roles = 'Anonymous';
  }
  else {
    $user_info->name = $user_to_show->name;
    $user_info->mail = $user_to_show->mail;
    $user_info->roles = implode(', ', $user_to_show->roles);
  }

  return $user_info;

}

/**
 * Custom format function.
 *
 * @param int $format
 *   Format.
 * @param object $user_info
 *   User info.
 *
 * @return array
 *   Render array.
 */
function d7_customblock_content_format($format, $user_info) {
  if ($format == 0) {

    $content = array(
      '#markup' => '<p><strong>Name:</strong> ' . $user_info->name . '<br>' .
      '<strong>Mail:</strong> ' . $user_info->mail . '<br><strong>Roles:</strong> ' .
      $user_info->roles . '</p>',
    );

  }
  else {

    $vars_userinfo = get_object_vars($user_info);
    $items = array();
    foreach ($vars_userinfo as $key => $value) {
      $items[] = ltrim($key, '_') . ': ' . $value;
    }

    $content = array(
      '#title' => t('User info'),
      '#items' => $items,
      '#theme' => 'item_list__d7_customblock_userinfo',
    );
  }

  return $content;
}
