<?php

/**
 * @file
 * A block module that displays user name and role.
 */

/**
 * Implements hook_help().
 */
function d7_customblock_help($path, $arg) {
  switch ($path) {
    case "admin/help#customblock":
      return t("Displays user name and role");

    break;
  }
}

/**
 * Implements hook_menu().
 */
function d7_customblock_menu() {
  $items = array();

  $items['d7_customblock/user-info'] = array(
    'title' => 'User name and role',
    'description' => 'Displays user name and role',
    'page callback' => 'd7_customblock_info_page',
    'access callback' => 'user_access',
    'access arguments' => array('access content'),
    'type' => MENU_NORMAL_ITEM,
  );

  $items['admin/config/people/user-info'] = array(
    'title' => 'User info',
    'description' => 'Configuration for d7 customblock module',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('d7_customblock_form'),
    'access arguments' => array('access administration configuration'),
    'type' => MENU_NORMAL_ITEM,
  );

  return $items;
}

/**
 * Page callback: User info.
 */
function d7_customblock_info_page() {

  $default_id = variable_get('d7_customblock_uid', 0);
  $user_info = d7_customblock_user_info($default_id);

  $content = '<p><strong>Name:</strong> ' . $user_info->name . '<br>' .
    '<strong>Mail:</strong> ' . $user_info->mail . '<br><strong>Roles:</strong> ' .
    $user_info->roles . '</p>';
  return $content;
}

/**
 * Page callback: d7 customblock settings.
 */
function d7_customblock_form($form, &$form_state) {

  $form['d7_customblock_uid'] = array(
    '#type' => 'textfield',
    '#title' => t('User id'),
    '#default_value' => variable_get('d7_customblock_uid', 0),
    '#size' => 2,
    '#maxlength' => 2,
    '#description' => t('Default user id.'),
    '#required' => TRUE,
  );

  return system_settings_form($form);
}

/**
 * Implements hook_block_info().
 */
function d7_customblock_block_info() {
  $blocks['customblock'] = array(
    // The name that will appear in the block list.
    'info' => t('User name and role'),
    'status' => TRUE,
    'region' => 'sidebar_first',
    // Default setting.
    'cache' => DRUPAL_CACHE_PER_ROLE,
    // Block shown only in nodes
    // 'visibility' => BLOCK_VISIBILITY_LISTED,
    // 'pages' => 'node/*',.
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function d7_customblock_block_view($delta = '') {

  switch ($delta) {
    case 'customblock':

      $default_id = variable_get('d7_customblock_uid', 0);
      $user_info = d7_customblock_user_info($default_id);

      $block_content = '<p><strong>Name:</strong> ' . $user_info->name . '<br>' .
        '<strong>Mail:</strong> ' . $user_info->mail . '<br><strong>Roles:</strong> ' .
        $user_info->roles . '</p>';

      $block = [
        'subject' => t('User details'),
        'content' => [
          '#markup' => $block_content,
        ],
      ];

      return $block;
  }

}

/**
 * Custom content function.
 *
 * @param int $default_uid
 *   User id.
 *
 * @return Object
 *   User info.
 */
function d7_customblock_user_info($default_uid) {

  $user_info = new stdClass();

  $user_to_show = user_load($default_uid);

  if (($user_to_show === FALSE) or ($default_uid == 0)) {
    $user_info->name = t('Anonimous user');
    $user_info->mail = '-';
    $user_info->roles = 'Anonymous';
  }
  else {
    $user_info->name = $user_to_show->name;
    $user_info->mail = $user_to_show->mail;
    $user_info->roles = implode(', ', $user_to_show->roles);
  }

  return $user_info;

}
